name: default
default-channel: g
default-listen: [g, local_announce, net_announce]
strings:
  player-welcome: '&aWelcome &e%player% &ato the server!'
  player-join: '%prefix%%player% &ehas joined &7%server%&e!'
  player-quit: '%prefix%%player% &ehas left &7%server%&e!'
  message: '{&7%server%&f} <%channel%&f> [%rank%&f] %player%: &7%message%'
  action: '{&7%server%&f} <%channel%&f> * %prefix%%player% &f%message%'